language: rust

os:
  - linux
  - osx

rust:
  - stable

script:
  - cargo test -vv

addons:
  apt:
    packages:
      - gfortran
  homebrew:
    packages:
      - gcc@9

notifications:
  email: false
