language: rust

os:
  - linux
  - osx

rust:
  - stable

script:
  - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then export CC=gcc-9 FC=gfortran-9 LIBRARY_PATH=/usr/local/opt/gcc/lib/gcc/9; fi
  - cargo test -vv

addons:
  apt:
    packages:
      - gfortran
  homebrew:
    packages:
      - gcc@9

notifications:
  email: false
