[package]
name = "openblas-src"
version = "0.5.1"
license = "Apache-2.0/MIT"
authors = [
  "Corey Richardson <corey@octayn.net>",
  "Ivan Ukhov <ivan.ukhov@gmail.com>",
  "Steve Harris <steveOfAR@gmail.com>",
]
description = "The package provides BLAS and LAPACK using the OpenBLAS implementation."
homepage = "https://github.com/cmr/openblas-src"
repository = "https://github.com/cmr/openblas-src"
build = "build.rs"
links = "openblas"

[features]
default = ["cblas"]

cblas = []
static = []
system = []
