[package]
name = "openblas-provider"
version = "0.0.5"
authors = ["Corey Richardson <corey@octayn.net>", "Ivan Ukhov <ivan.ukhov@gmail.com>"]
links = "openblas"
build = "build.rs"
repository = "https://github.com/cmr/openblas-provider"
license = "BSL-1.0"
description = "BLAS/LAPACK provider using the OpenBLAS implementation"

[lib]
name = "openblas_provider"
path = "lib.rs"

[features]
static-openblas = []
system-openblas = []

[dependencies]
libc = "*"
