[package]
name = "openblas-provider"
version = "0.3.0"
license = "Apache-2.0/MIT"
authors = [
  "Corey Richardson <corey@octayn.net>",
  "Ivan Ukhov <ivan.ukhov@gmail.com>",
]
description = "The package provides BLAS and LAPACK using the OpenBLAS implementation."
homepage = "https://github.com/cmr/openblas-provider"
repository = "https://github.com/cmr/openblas-provider"
links = "openblas"
build = "build.rs"

[features]
default = ["include-cblas"]

include-cblas = []
static-openblas = []
system-openblas = []
