name: Rust

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  windows-msvc:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v2
      with:
        path: ./vcpkg
        key: vcpkg-openblas
    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git --depth 1
        cd vcpkg
        ./bootstrap-vcpkg.bat
    - name: Install OpenBLAS by vcpkg
      run: |
        ./vcpkg/vcpkg.exe install openblas:x64-windows-static
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features=system,static
      env:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg

  windows-gnu:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: msys2 setup
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            git curl make
            mingw-w64-x86_64-toolchain
      - name: rustup install
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-host x86_64-pc-windows-gnu
          export PATH=$USERPROFILE/.cargo/bin:$PATH
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features=static

  linux:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        feature:
          - static
          - system
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: >
          --no-default-features
          --features=${{ matrix.features }}
